catalog/urls.py
from django.urls import include, path
from .views import home, students, main, teachers, to_competition

# urlpatterns = [
#     path('', index, name='home'),
#     path('students/', include((
#         [path('', students.CompetitionView.as_view(), name='competition_list'),
#          ]
#         , 'catalog'), namespace='student'))
#
# ]
urlpatterns = [
    path('', home, name='home'),
    path('competitions/', to_competition, name='to_competition'),

    path('students/', include(([
                                   path('main/', students.CompetitionView.as_view(), name='competition_list'),
                                   path('room/', students.PersonalAccountView.as_view(), name='my_account'),
                                   path('add_competition/<int:pk>/', students.add_new_comp, name='add_new_competition'),
                                   path('taken/', students.TakenCompetitionListView.as_view(), name='take_competition'),
                                   # path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
                                   path('add_decision/<int:pk>/', students.model_form_upload,
                                        name='download_answer_file'),
                                   path('down_test_data/<int:pk>', students.download_competition_test_data,
                                        name='download_test_data'),
                                   path('down_study_data/<int:pk>', students.download_competition_study_data,
                                        name='download_study_data'),
                                   path('down_model_data/<int:pk>', students.download_answer_model,
                                        name='download_model_data'),
                                   path('down_answer_data/<int:pk>', students.download_answer_data,
                                        name='download_answer_data'),
                                   path('competition/<int:pk>', students.one_competition, name='one_competition')
                               ], 'catalog'), namespace='students')),

    path('teachers/', include(([
                                   path('', teachers.CompetitionView.as_view(), name='competition_list'),
                                   path('competition/add/', teachers.add_new_competition,
                                        name='add_new_competition'),
                                   path('competition/<int:pk>', teachers.one_competition, name='one_competition')
                                   # path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
                                   # path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
                                   # path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
                                   # path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
                                   # path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
                                   # path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
                               ], 'catalog'), namespace='teachers')),
    # path('down/', main.CreatePostView.as_view(), name='download'),
]

djangoProject/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings



from catalog.views import students, main, teachers

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', main.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/views.py
from django.shortcuts import render
# from .models import User
# Create your views here.
def index(request):
    # num_users = User.objects.all().count()
    num_users = 10
    return render(
        request,
        'index.html',
        context={'num_users': num_users},
    )

catalog/views/students.py
import os

from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.encoding import smart_str
from django.views.generic import CreateView, ListView, UpdateView

from ..decorators import student_required
from ..forms import StudentSignUpForm, DownAnswerFileForm, ColabHrefForm
from catalog.models import Student, User, Competition, TakenCompetitionn, \
    AnswerFile, CompetitionFile, ColabHref, Subject
from ..check_answer import binary_class


class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


@method_decorator([login_required, student_required], name='dispatch')
class CompetitionView(ListView):
    model = Competition
    ordering = ('date_of_start',)
    context_object_name = 'competitions'
    template_name = './students/competition_list.html'

    def get_queryset(self):
        queryset = Competition.objects.all().select_related('subject')
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class TakenCompetitionListView(ListView):
    model = TakenCompetitionn
    context_object_name = 'taken_competitions'
    template_name = './students/taken_competition_list.html'

    def get_queryset(self):
        queryset = self.request.user.student.take_competition_student \
            .select_related('competition', 'competition__subject') \
            .order_by('competition__date_of_finish')
        return queryset


@login_required
def model_form_upload(request, pk):
    competition = get_object_or_404(Competition, pk=pk)
    student = request.user.student

    if request.method == 'POST':
        my_model = 0
        try:
            my_model = AnswerFile.objects.get(student=student, competition=competition)
        except:
            print("нет")
        # if my_model != 0:
        #     return redirect('students:take_competition')
        my_href = 0
        try:
            my_href = ColabHref.objects.get(student=student, competition=competition)
        except:
            print("нет!")

        if my_href != 0 and my_model != 0:
            return redirect('students:take_competition')
        my_href = 0
        try:
            my_href = request.POST['href']
        except:
            print('yyyyyy')
        if my_href != 0:
            ColabHref.objects.create(student_id=request.user.id, competition_id=competition.id,
                                     href=my_href)
            return render(request, './students/add_answer_file.html', {
                'form': DownAnswerFileForm(),
                'form1': ColabHrefForm(),
            })
        else:
            try:
                a = request.POST['is_public']
                is_public = True
            except:
                is_public = False

            user_answer_file_name = AnswerFile.objects.create(student_id=request.user.id,
                                                              competition_id=competition.id,
                                                              model_file=request.FILES['model_file'],
                                                              data_file=request.FILES['data_file'],
                                                              is_public=is_public).data_file
            true_answer_file_name = get_object_or_404(CompetitionFile, competition=competition).true_answer_file
            points = binary_class(true_answer_file_name, user_answer_file_name)
            TakenCompetitionn.objects.filter(student=student, competition=competition).update(score=points)
            Student.objects.filter(user_id=request.user.id).update(points=student.points + points)
            return redirect('students:take_competition')
    else:
        return render(request, './students/add_answer_file.html', {
            'form': DownAnswerFileForm(),
            'form1': ColabHrefForm(),
        })


@method_decorator([login_required, student_required], name='dispatch')
class PersonalAccountView(ListView):  # новый
    model = Student
    context_object_name = 'user_data'
    template_name = './students/personal_account.html'

    def get_queryset(self):
        # queryset = self.request.user.student.take_competition_student \
        #     .select_related('competition', 'competition__subject') \
        #     .order_by('competition__date_of_finish')
        # queryset = self.request.user.take_competition_student.select_related('competition', 'student')
        queryset = Student.objects.select_related('user').get(user=self.request.user)
        p = Student.objects.select_related('user').get(user=self.request.user)
        print(p.user.first_name)
        return queryset


@login_required
def add_new_comp(request, pk):
    competition = get_object_or_404(Competition, pk=pk)
    student = request.user.student
    maybeComp = 0
    try:
        maybeComp = TakenCompetitionn.objects.get(student=student, competition=competition)
    except:
        print("maybeComp not")
    if maybeComp == 0:
        TakenCompetitionn.objects.create(student=student, competition_id=competition.id, score=0)
    return redirect('students:take_competition')


@login_required
def download_competition_test_data(request, pk):
    comp = CompetitionFile.objects.get(competition_id=pk)
    path_to_file = comp.test_file.path
    filename = os.path.basename(path_to_file)
    response = HttpResponse(comp.data_file, content_type='application/msword')
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(filename)
    response['X-Sendfile'] = smart_str(path_to_file)
    return response


@login_required
def download_competition_study_data(request, pk):
    comp = CompetitionFile.objects.get(competition_id=pk)
    path_to_file = comp.data_file.path
    filename = os.path.basename(path_to_file)
    response = HttpResponse(comp.data_file, content_type='application/msword')
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(filename)
    response['X-Sendfile'] = smart_str(path_to_file)
    return response


@login_required
def download_answer_model(request, pk):
    comp = get_object_or_404(AnswerFile, competition_id=pk)
    path_to_file = comp.data_file.path
    filename = os.path.basename(path_to_file)
    response = HttpResponse(comp.data_file, content_type='multipart/form-data')
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(filename)
    response['X-Sendfile'] = smart_str(path_to_file)
    return response


@login_required
def download_answer_data(request, pk):
    comp = AnswerFile.objects.get(competition_id=pk)
    path_to_file = comp.data_file.path
    filename = os.path.basename(path_to_file)
    response = HttpResponse(comp.data_file, content_type='multipart/form-data')
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(filename)
    response['X-Sendfile'] = smart_str(path_to_file)
    return response


@student_required
def one_competition(request, pk):
    competition = get_object_or_404(Competition, pk=pk)
    student = request.user.student

    maybeColabHref = 0
    try:
        maybeColabHref = ColabHref.objects.get(student=student, competition=competition)
    except:
        print("maybeComp not")

    answerFiles = 0
    try:
        answerFiles = AnswerFile.objects.get(student=student, competition=competition)
    except:
        print("answerFiles not")

    competitionfile = 0
    try:
        competitionfile = CompetitionFile.objects.get(competition=competition)
    except:
        print("competitionfile not")

    otherAnswerFiles = 0
    try:
        otherAnswerFiles = AnswerFile.objects.exclude(student=student).filter(competition=competition,
                                                                              is_public=True).select_related('student',
                                                                                                             'student__user')
    except:
        print('otherAnswerFiles not')

    subject = competition.subject.name
    author = competition.author.username
    if maybeColabHref != 0:
        if answerFiles != 0:
            return render(request, './students/one_comp.html', {
                'author': author,
                'subject': subject,
                'competition': competition,
                'colabHref': maybeColabHref,
                'answerFiles': answerFiles,
                'competitionfile': competitionfile,
                'otherAnswerFiles': otherAnswerFiles
            })
        else:
            return render(request, './students/one_comp.html', {
                'author': author,
                'subject': subject,
                'competition': competition,
                'colabHref': maybeColabHref,
                'competitionfile': competitionfile,
                'otherAnswerFiles': otherAnswerFiles
            })
    else:
        if answerFiles != 0:
            return render(request, './students/one_comp.html', {
                'author': author,
                'subject': subject,
                'competition': competition,
                'answerFiles': answerFiles,
                'competitionfile': competitionfile,
                'otherAnswerFiles': otherAnswerFiles
            })
        else:
            return render(request, './students/one_comp.html', {
                'author': author,

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/../../static/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="">All books</a></li>
          <li><a href="">All authors</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/i1.html
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
</head>

<body>
  {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
  {% block content %}<!-- default content text (typically empty) -->{% endblock %}
</body>
</html>

catalog/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>UniMo</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="{% static 'img/graduated.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/graduated.png' %}">
    <!-- Load Require CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Font CSS -->
    {#    <link href="https://github.com/Mary230/diplom/blob/main/boxicon.min.css" rel="stylesheet" type="application/x-pointplus">#}
    <link href="{% static 'css/boxicon.min.css' %}" rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <!-- Load Tempalte CSS -->
    <link rel="stylesheet" href="{% static 'css/templatemo.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <!--

    TemplateMo 561 Purple Buzz

    https://templatemo.com/tm-561-purple-buzz

    -->

</head>

<body>
<!-- Header -->
<nav id="main_nav" class="navbar navbar-expand-lg navbar-light bg-white shadow">
    <div class="container d-flex justify-content-between align-items-center">
        <a class="navbar-brand h1" href="{% url 'home' %}">

            <span class="text-primary h4">UNI</span> <span class="home-text-banner h4">MO</span>
        </a>
        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbar-toggler-success" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between"
             id="navbar-toggler-success">
            <div class="flex-fill mx-xl-5 mb-2">
                <ul class="nav navbar-nav d-flex justify-content-between mx-xl-5 text-center text-dark">
                    <li class="nav-item">
                        <a class="nav-link btn-outline-primary rounded-pill px-3" href="{% url 'home' %}">Соревнования</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-primary rounded-pill px-3" href="about.html">Блог</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-primary rounded-pill px-3" href="work.html"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-primary rounded-pill px-3" href="pricing.html"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-outline-primary rounded-pill px-3" href="contact.html"></a>
                    </li>

                </ul>
            </div>
            <div class="navbar align-self-center d-flex">
                {#                <a class="nav-link" href="#"><i class='bx bx-bell bx-sm bx-tada-hover text-primary'></i></a>#}
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'students:my_account' %}"><i class='bx bx-user bx-sm text-primary'></i></a>
                    <a class="nav-link" href="{% url 'logout' %}"><i
                            class='bx bx-log-out bx-sm text-primary'></i></a>
                {% else %}
                    <a class="nav-link" href="{% url 'signup' %}"><i
                            class='bx bx-user-circle bx-sm text-primary'></i></a>
                    <a class="nav-link" href="{% url 'login' %}"><i class='bx bx-log-in bx-sm text-primary'></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
<!-- Close Header -->

{% block content %}
{% endblock %}


</html>

catalog/templates/post.html
<!-- templates/post.html -->
<h1>Create Post Page</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit New Post</button>
</form>