catalog/urls.py
from django.urls import include, path
from .views import home, students, main, teachers, to_competition

# urlpatterns = [
#     path('', index, name='home'),
#     path('students/', include((
#         [path('', students.CompetitionView.as_view(), name='competition_list'),
#          ]
#         , 'catalog'), namespace='student'))
#
# ]
urlpatterns = [
    path('', home, name='home'),
    path('competitions/', to_competition, name='to_competition'),

    path('students/', include(([
                                   path('main/', students.CompetitionView.as_view(), name='competition_list'),
                                   path('room/', students.PersonalAccountView.as_view(), name='my_account'),
                                   path('add_competition/<int:pk>/', students.add_new_comp, name='add_new_competition'),
                                   path('taken/', students.TakenCompetitionListView.as_view(), name='take_competition'),
                                   # path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
                                   path('add_decision/<int:pk>/', students.model_form_upload,
                                        name='download_answer_file'),
                                   path('down_test_data/<int:pk>', students.download_competition_test_data,
                                        name='download_test_data'),
                                   path('down_study_data/<int:pk>', students.download_competition_study_data,
                                        name='download_study_data'),
                                   path('down_model_data/<int:pk>', students.download_answer_model,
                                        name='download_model_data'),
                                   path('down_answer_data/<int:pk>', students.download_answer_data,
                                        name='download_answer_data'),
                                   path('competition/<int:pk>', students.one_competition, name='one_competition')
                               ], 'catalog'), namespace='students')),

    path('teachers/', include(([
                                   path('', teachers.CompetitionView.as_view(), name='competition_list'),
                                   path('competition/add/', teachers.add_new_competition,
                                        name='add_new_competition'),
                                   path('competition/<int:pk>', teachers.one_competition, name='one_competition')
                                   # path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
                                   # path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
                                   # path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
                                   # path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
                                   # path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
                                   # path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
                               ], 'catalog'), namespace='teachers')),
    # path('down/', main.CreatePostView.as_view(), name='download'),
]

djangoProject/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings



from catalog.views import students, main, teachers

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', main.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from datetime import datetime

from django.db import models
# from django.contrib.auth.models import User
from django.utils.html import escape, mark_safe


class Competition(models.Model):
    id = models.AutoField(primary_key=True, null=False, unique=True, editable=False)
    name = models.CharField(max_length=100, help_text=('Введите название соревнования'))
    desc = models.TextField(help_text=('Введите описание соревнования'), null=False)
    author = models.ForeignKey("User", on_delete=models.SET_NULL, null=True)
    subject = models.ForeignKey("Subject", on_delete=models.SET_NULL, null=True)
    state_list = (
        ('w', 'Планируется'),
        ('n', 'Проходит'),
        ('f', 'Завершилось'),
    )
    state = models.CharField(max_length=1, help_text=('Укажите состояние, в котором находится соревнование'),
                             choices=state_list,
                             default='w')
    complexity_list = (
        ('e', 'Легкий'),
        ('n', 'Средний'),
        ('d', 'Сложный'),
    )
    complexity = models.CharField(max_length=1, help_text=('Укажите сложность соревнования'),
                                  choices=complexity_list, default='e')

    date_of_start = models.DateTimeField(default=datetime.now)
    date_of_finish = models.DateTimeField(default=datetime.now)


from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    email = models.EmailField(max_length=254, default='000@rr.ru')


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    competition = models.ManyToManyField(Competition, related_name='competitions')
    groupe = models.CharField(max_length=8, help_text='Укажите номер группы в формате 00-000', null=True)

    institute = (
        ('КФУ', 'Казанский Федеральный Университет'),
        ('ИЭИП', "Институт экологии и природопользования"),
        ('ИГНТ', "Институт геологии и нефтегазовых технологий"),
        ('ИММЛ', "Институт математики и механики им.Н.И.Лобачевского"),
        # "Институт физики",
        # "Химический институт им.А.М.Бутлерова",
        # "Юридический факультет",
        # "Институт вычислительной математики и информационных технологий",
        # "Институт филологии и межкультурной коммуникации",
        # "Институт психологии и образования",
        # "Общеуниверситетская кафедра физического воспитания и спорта",
        # "Институт информационных технологий и интеллектуальных систем",
        # "Институт фундаментальной медицины и биологии",
        # "Инженерный институт",
        # "Институт международных отношений",
        # "Высшая школа бизнеса",
        # "Институт социально-философских наук и массовых коммуникаций",
        # "Институт управления, экономики и финансов",
        # "Высшая школа государственного и муниципального управления",
        # "Центр цифровых трансформаций",
        # "Институт передовых образовательных технологий"
    )
    university_name = models.CharField(max_length=50, choices=institute,
                                       help_text=('Укажите полное название вашего института'), default='КФУ')
    points = models.IntegerField(default=0, editable=False)

    def display_list_competition(self):
        return ', '.join([competition.name for competition in self.competition.all()[:3]])

    display_list_competition.short_description = 'List of Competitions'


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    student_list = models.ManyToManyField(Student, help_text=('Select your students'))
    subject = models.CharField(max_length=70)

    def display_list_students(self):
        return ', '.join([student.user.username for student in self.student_list.all()])

    display_list_students.short_description = 'List of Students'
    institute = (
        ('КФУ', 'Казанский Федеральный Университет'),
        ('ИЭИП', "Институт экологии и природопользования"),
        ('ИГНТ', "Институт геологии и нефтегазовых технологий"),
        ('ИММЛ', "Институт математики и механики им.Н.И.Лобачевского"),
        # "Институт физики",
        # "Химический институт им.А.М.Бутлерова",
        # "Юридический факультет",
        # "Институт вычислительной математики и информационных технологий",
        # "Институт филологии и межкультурной коммуникации",
        # "Институт психологии и образования",
        # "Общеуниверситетская кафедра физического воспитания и спорта",
        # "Институт информационных технологий и интеллектуальных систем",
        # "Институт фундаментальной медицины и биологии",
        # "Инженерный институт",
        # "Институт международных отношений",
        # "Высшая школа бизнеса",
        # "Институт социально-философских наук и массовых коммуникаций",
        # "Институт управления, экономики и финансов",
        # "Высшая школа государственного и муниципального управления",
        # "Центр цифровых трансформаций",
        # "Институт передовых образовательных технологий"
    )
    university_name = models.CharField(max_length=50, choices=institute,
                                       help_text=('Укажите полное название вашего института'), default='КФУ')


class TakenCompetitionn(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='take_competition_student')
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, related_name='take_competition_competition')
    score = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)


class Subject(models.Model):
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=7, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)


class CompetitionFile(models.Model):
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, related_name='competition_with_file')
    test_file = models.FileField(null=True)
    data_file = models.FileField(null=True)
    true_answer_file = models.FileField(null=True)


class AnswerFile(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='user_of_answer')
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, related_name='competition_to_answer')
    model_file = models.FileField(null=True)
    data_file = models.FileField(null=True)
    is_public = models.BooleanField(default=True)
    is_copy = models.BooleanField(default=False)

class ColabHref(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='user_colab')
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, related_name='competition_colab')
    href = models.CharField(max_length=150)

catalog/views.py
from django.shortcuts import render
# from .models import User
# Create your views here.
def index(request):
    # num_users = User.objects.all().count()
    num_users = 10
    return render(
        request,
        'index.html',
        context={'num_users': num_users},
    )

catalog/views/teachers.py
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views.generic import CreateView
from ..forms import TeacherSignUpForm, AddNewCompetitionForm, AddCompetitionFileForm
from ..models import User, Competition, ColabHref, AnswerFile, CompetitionFile, Subject, Teacher, TakenCompetitionn
from ..decorators import teacher_required
from django.views.generic import CreateView, ListView, UpdateView
from ..check_answer import binary_class


class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


@method_decorator([login_required, ], name='dispatch')
class CompetitionView(ListView):
    model = Competition
    ordering = ('date_of_start',)
    context_object_name = 'competitions'
    template_name = './teachers/competition_list.html'

    def get_queryset(self):
        user = self.request.user
        queryset = Competition.objects.all().filter(author=user)
        return queryset



@login_required
def one_competition(request, pk):
    competition = get_object_or_404(Competition, pk=pk)
    maybeColabHref = 0
    try:
        maybeColabHref = ColabHref.objects.all().filter(competition=competition).select_related('student')
    except:
        print("maybeComp not")
    answerFiles = 0
    try:
        answerFiles = AnswerFile.objects.filter(competition=competition).select_related('student', 'student__user')
    except:
        print("answerFiles not")
    points = 0
    try:
        points = TakenCompetitionn.objects.filter(competition=competition).select_related('student',
                                                                                          'student__user').order_by(
            '-student')
    except:
        print("answerFiles not")
    competitionfile = 0
    try:
        competitionfile = CompetitionFile.objects.get(competition=competition)
    except:
        print("competitionfile not")
    subject = competition.subject.name
    author = competition.author.username

    if maybeColabHref != 0:
        if answerFiles != 0:
            return render(request, './teachers/one_comp.html', {

                'subject': subject,
                'competition': competition,
                'colabHref': maybeColabHref,
                'answerFiles': answerFiles,
                'competitionfile': competitionfile,
                'points':points,
            })
        else:
            return render(request, './teachers/one_comp.html', {

                'subject': subject,
                'competition': competition,
                'colabHref': maybeColabHref,
                'competitionfile': competitionfile,
                'points': points,
            })
    else:
        if answerFiles != 0:
            return render(request, './teachers/one_comp.html', {

                'subject': subject,
                'competition': competition,
                'answerFiles': answerFiles,
                'competitionfile': competitionfile,
                'points': points,
            })
        else:
            return render(request, './teachers/one_comp.html', {

                'subject': subject,
                'competition': competition,
                'competitionfile': competitionfile,
                'points': points,
            })


@login_required
def add_new_competition(request):
    if request.method == 'POST':
        print(request.POST)
        comp_name = request.POST['name']
        comp_desc = request.POST['desc']
        comp_subject = request.POST['subject']
        subject = get_object_or_404(Subject, name=comp_subject)
        comp_state = request.POST['state']
        comp_complexity = request.POST['complexity']
        test_file = request.POST['test_file']
        data_file = request.POST['data_file']
        true_answer_file = request.POST['true_answer_file']
        competition = Competition.objects.create(name=comp_name, desc=comp_desc, author_id=request.user.id,
                                                 subject_id=subject.id,
                                                 state=comp_state, complexity=comp_complexity)
        CompetitionFile.objects.create(competition_id=competition.id, test_file=test_file, data_file=data_file,
                                       true_answer_file=true_answer_file)
        return redirect('teachers:competition_list')
    else:
        return render(request, './teachers/ad_new_competition.html', {
            'form': AddNewCompetitionForm(),
            'form1': AddCompetitionFileForm(),
        })

catalog/templates/students/competition_list.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <div class="banner-wrapper bg-light">
        <div id="index_banner" class="banner-vertical-center-index container-fluid pt-5"
             style="background-image: url('{% static 'img/home-banner.jpeg' %}'); height: 100vh">
        <a href="{% url 'students:take_competition'%}" class="btn btn-outline-dark mb-2" style="margin-left: 80%">
            Мои соревнования</a>
            <div class="card" style="max-width: 85%; margin: auto">

                <table class="table mb-0">
                    <thead>
                    <tr class="h-50">
                        <th>Название соревнования</th>
                        <th>Сложность</th>
                        <th>Дата старта</th>

                        <th>Тип</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for comp in competitions %}
                        {% if comp.state == 'n' %}
                            <tr>
                            <td class="align-middle">{{ comp.name }}</td>
                            {% if comp.complexity == 'e' %}
                                <td class="align-middle" style="color: rgba(1,70,0,0.85)"> Легкий</td>
                            {% elif comp.complexity == 'n' %}
                                <td class="align-middle" style="color: rgb(178,127,0)"> Средний</td>
                            {% else %}
                                <td class="align-middle" style="color: rgba(132,0,0,0.85)"> Сложный</td>
                            {% endif %}
                            <td class="align-middle">{{ comp.date_of_finish|date }} </td>
                            <td class="align-middle"
                                style="color: {{ comp.subject.color }} ">{{ comp.subject.name }} </td>

                            <td class="text-middle">
                                <a href="{% url 'students:add_new_competition' comp.id %}" class="btn btn-primary ">Начать→</a>
                            </td>
                        {% endif %}
                    </tr>
                    {% empty %}
                        <tr>
                            <td class="bg-light text-center font-italic" colspan="4">У вас пока нет соревнований :(
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/students/one_comp.html
{% extends 'index.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="banner-wrapper bg-light">
        <div id="index_banner1" class="banner-vertical-center-index container-fluid pt-2"
             style=" min-height: 80vh">
            <div class=" container mt-4">
                <a href="{% url 'students:take_competition' %}"
                   class="btn btn-outline-dark mb-2">Вернуться к списку
                    соревнований</a>
                <div class="row mt-3">
                    <div class="col-sm">
                        <ul class="list-group">
                            <li class="list-group-item">Название: {{ competition.name }}</li>
                            <li class="list-group-item">Тип задачи: {{ subject }}</li>
                            <li class="list-group-item">Автор: {{ author }}</li>
                            <li class="list-group-item">Предмет: {% if competition.complexity == 'e' %}Легкий
                            {% elif competition.complexity == 'n' %}Средний{% else %}Сложный{% endif %}
                            </li>
                            <li class="list-group-item">Дата старта: {{ competition.date_of_start }}</li>
                            <li class="list-group-item">Дата окончания: {{ competition.date_of_finish }}</li>
                        </ul>
                    </div>
                    <div class="col-sm">
                        <ul class="list-group " style="min-height: 100%">
                            {% if competitionfile %}
                                <li class="list-group-item pb-0">
                                    <p class="p-0">Данные cоревнования:</p>
                                </li>
                                <li class="list-group-item">
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{% url 'students:download_study_data' competition.id %}"
                                           class="btn btn-outline-warning">Скачать обучающие данные</a>

                                        <a href="{% url 'students:download_test_data' competition.id %}"
                                           class="btn btn-outline-warning">Скачать тестовые данные</a>
                                    </div>
                                </li>
                            {% endif %}
                            {% if answerFiles %}
                                <li class="list-group-item pb-0">
                                    <p class="font-weight-light">Мои ответы:</p>
                                </li>
                                <li class="list-group-item">
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{% url 'students:download_model_data' competition.id %}"
                                           class="btn btn-outline-primary" data-toggle="tooltip" data-placement="top"
                                           title="{{ answerFiles.model_file }}">Модель
                                        </a>

                                        <a href="{% url 'students:download_answer_data' competition.id %}"
                                           class="btn btn-outline-primary" data-toggle="tooltip" data-placement="top"
                                           title="{{ answerFiles.data_file }}">Данные
                                        </a>
                                    </div>
                                </li>
                                {% else %}
                                <a href="{% url 'students:download_answer_file' competition.id %}"
                                   class="btn btn-primary mt-3">Загрузить ответ</a>
                            {% endif %}
                            {% if colabHref %}
                                <li class="list-group-item">
                                    <a href="{{ colabHref.href }}" data-toggle="tooltip" data-placement="top"
                                       title="{{ colabHref.href }}"
                                    >Ссылка на Google Colab</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>

                </div>
                <div class="row pt-5">
                    <div class="col-sm">
                        <ul class="list-group">
                            <li class="list-group-item">Описание:
                                <hr>
                                {{ competition.desc }}</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="service-tag py-4 mt-lg-5  mb-lg-5 bg-secondary">
                <div class="col-md-12">
                    <ul class="nav d-flex justify-content-center">
                        <li class="nav-item mx-lg-4">
                            <h1 class="banner-heading h3 text-light display-3 mb-0  mx-0 px-0">Ответы пользователей</h1>
                        </li>
                    </ul>
                </div>
            </div>


        </div>
    </div>
    <div class="card container mb-lg-5 pt-lg-2" style="margin: auto;background-color: #f6f9fe">
        <table class="table ">
            <thead>
            <tr class="h-50">
                <th>Пользователь</th>
                <th>Модель</th>
                <th>Ссылка на внешний источник</th>
            </tr>
            </thead>
            <tbody>
            {% for an in otherAnswerFiles %}
                <tr>
                    <td class="align-middle">
                        {{ an.student.user.first_name }} {{ an.student.user.last_name }}
                        ({{ an.student.user.email }})
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'students:download_model_data' competition.id %}"
                           class="btn btn-outline-primary px-xxl-5" data-toggle="tooltip"
                           data-placement="top"
                           title="{{ an.model_file }}">Скачать модель
                        </a>
                    </td>
                    <td>
                        <a href="#" data-toggle="tooltip" data-placement="top"
                           title="Ссылка на Google Colab"
                        >Ссылка на Google Colab</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td class="bg-light text-center font-italic" colspan="4">Готовых моделей пока нет
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    </div>
{% endblock %}

catalog/templates/students/personal_account.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="banner-wrapper bg-light">
        <div id="index_banner" class="banner-vertical-center-index container-fluid pt-5"
             style="background-image: url('{% static 'img/home-banner.jpeg' %}'); height: 100vh">
            <div class="p-5 rounded" style="
    margin-left: 20%;
    margin-right: 30%;
background: rgba(255,255,255,0.62)">
{#                {% for data in user_data %}#}
                    <h1>{{ user_data.user.firstname }}</h1>
{#                {% endfor%}#}
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/students/taken_competition_list.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="banner-wrapper bg-light">
        <div id="index_banner" class="banner-vertical-center-index container-fluid pt-2"
             style="background-image: url('{% static 'img/home-banner.jpeg' %}'); min-height: 100vh">
        <a href="{% url 'students:competition_list'%}" class="btn btn-outline-dark mb-2">
            Вернуться к списку соревнований</a>
            <div class="card container" style="background-color: #f6f9fe">
                <table class="table mb-0">
                    <thead>
                    <tr>
                        <th>Соревнование</th>
                        <th>Очки</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for taken_competition in taken_competitions %}
                        <tr>
                            <td> <a href="{% url 'students:one_competition' taken_competition.competition.id %}"
                                    class="btn btn-light">{{ taken_competition.competition.name }}</a></td>

                            <td>{{ taken_competition.score }}</td>
                            <td class="text-right">
                                <a href="{% url 'students:download_study_data' taken_competition.competition.id %}"
                                   class="btn btn-outline-warning">Скачать обучающие данные</a>
                                <a href="{% url 'students:download_test_data' taken_competition.competition.id %}"
                                   class="btn btn-outline-warning">Скачать тестовые данные</a>
                            </td>
                            <td class="text-right">
                                <a href="{% url 'students:download_answer_file' taken_competition.competition.id %}"
                                   class="btn btn-primary">Загрузить ответ</a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="bg-light text-center font-italic" colspan="3">Вы пока не выбрали ни одного соревнования:(
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}